name: Ping URL Every 10 Minutes

on:
  # Runs every 10 minutes
  schedule:
    - cron: "*/5 * * * *"

  # Allows manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  ping-job:
    runs-on: ubuntu-latest

    steps:
      - name: Ping target URL
        run: |
          echo "Pinging URL at $(date)"
          curl --max-time 10 -f https://easy-buy-backend-nrwm.onrender.com
          echo "Ping successful"
